const CovidCardActionTypes = {
  REQUEST_DATA_START: "REQUEST_DATA_START",
  REQUEST_DATA_SUCCESS: "REQUEST_DATA_SUCCESS",
  REQUEST_DATA_FAILED: "REQUEST_DATA_FAILED",
};

export default CovidCardActionTypes;
