export const CountrySelectorActionTypes = {
  REQUEST_COUNTRY_DATA_PENDING: "REQUEST_COUNTRY_DATA_PENDING",
  REQUEST_COUNTRY_DATA_SUCCESS: "REQUEST_COUNTRY_DATA_SUCCESS",
  REQUEST_COUNTRY_DATA_FAILED: "REQUEST_COUNTRY_DATA_FAILED",
  HANDLE_COUNTRY_CHANGE: "HANDLE_COUNTRY_CHANGE",
};
